import { IAdaptable } from '../../types';
import { UserFilter } from '../../PredefinedConfig/UserFilterState';
import { AdaptableColumn } from '../../PredefinedConfig/Common/AdaptableColumn';
import { DataType } from '../../PredefinedConfig/Common/Enums';
import { NamedFilter } from '../../PredefinedConfig/NamedFilterState';
import { ColumnCategory } from '../../PredefinedConfig/ColumnCategoryState';
import { IFilterService } from './Interface/IFilterService';
import { ColumnFilter } from '../../PredefinedConfig/ColumnFilterState';
import { KeyValuePair } from '../Interface/KeyValuePair';
export declare const BLANKS_SYSTEM_FILTER = "Blanks";
export declare const NON_BLANKS_SYSTEM_FILTER = "Non Blanks";
export declare const TODAY_SYSTEM_FILTER = "Today";
export declare const IN_PAST_SYSTEM_FILTER = "In Past";
export declare const IN_FUTURE_SYSTEM_FILTER = "In Future";
export declare const YESTERDAY_SYSTEM_FILTER = "Yesterday";
export declare const TOMORROW_SYSTEM_FILTER = "Tomorrow";
export declare const NEXT_WORKING_DAY_SYSTEM_FILTER = "Next Working Day";
export declare const PREVIOUS_WORKING_DAY_SYSTEM_FILTER = "Previous Working Day";
export declare const THIS_YEAR_SYSTEM_FILTER = "This Year";
export declare const POSITIVE_SYSTEM_FILTER = "Positive";
export declare const NEGATIVE_SYSTEM_FILTER = "Negative";
export declare const ZERO_SYSTEM_FILTER = "Zero";
export declare const TRUE_SYSTEM_FILTER = "True";
export declare const FALSE_SYSTEM_FILTER = "False";
export declare class FilterService implements IFilterService {
    private adaptable;
    constructor(adaptable: IAdaptable);
    GetAllSystemFilters(): string[];
    GetUserFilters(userFilters: UserFilter[], userFilterNames: string[]): UserFilter[];
    GetSystemFiltersForColumn(column: AdaptableColumn, systemFilters: string[]): string[];
    GetUserFiltersForColumn(column: AdaptableColumn, userFilters: UserFilter[]): UserFilter[];
    GetNamedFiltersForColumn(column: AdaptableColumn, namedFilters: NamedFilter[], columnCategories: ColumnCategory[]): NamedFilter[];
    ShowUserFilterForColumn(UserFilters: UserFilter[], name: string, column: AdaptableColumn): boolean;
    GetColumnIdForUserFilter(userFilter: UserFilter): string;
    GetFunctionForSystemFilter(systemFilterName: string): any;
    GetDatatypeForSystemFilter(systemFilterName: string): DataType;
    ConvertColumnFiltersToKVPArray(columnFilters: ColumnFilter[], columns: AdaptableColumn[]): KeyValuePair[];
    GetColumnFiltersDescription(columnFilters: ColumnFilter[], columns: AdaptableColumn[]): string;
}
