import { IAdaptable } from '../../AdaptableInterfaces/IAdaptable';
import { ApplicationApi } from '../ApplicationAPI';
import { Glue42ApiImpl } from './Glue42ApiImpl';
import { AdaptableApi } from '../../types';
import { ActionColumnApi } from '../ActionColumnApi';
import { AdvancedSearchApi } from '../AdvancedSearchApi';
import { AlertApi } from '../AlertApi';
import { AuditEventApi } from '../AuditEventApi';
import { BulkUpdateApi } from '../BulkUpdateApi';
import { CalendarApi } from '../CalendarApi';
import { CalculatedColumnApi } from '../CalculatedColumnApi';
import { CellSummaryApi } from '../CellSummaryApi';
import { CellValidationApi } from '../CellValidationApi';
import { ChartApi } from '../ChartApi';
import { ColumnCategoryApi } from '../ColumnCategoryApi';
import { ColumnChooserAPI } from '../ColumnChooserAPI';
import { ColumnFilterApi } from '../ColumnFilterApi';
import { ConditionalStyleApi } from '../ConditionalStyleApi';
import { ConfigApi } from '../ConfigApi';
import { CustomSortApi } from '../CustomSortApi';
import { DashboardApi } from '../DashboardApi';
import { ToolPanelApi } from '../ToolPanelApi';
import { DataSourceApi } from '../DataSourceApi';
import { EntitlementsApi } from '../EntitlementsApi';
import { EventApi } from '../EventApi';
import { PluginsApi } from '../PluginsApi';
import { ExportApi } from '../ExportApi';
import { FlashingCellApi } from '../FlashingCellApi';
import { UpdatedRowApi } from '../UpdatedRowApi';
import { FormatColumnApi } from '../FormatColumnApi';
import { FreeTextColumnApi } from '../FreeTextColumnApi';
import { InternalApi } from '../InternalApi';
import { LayoutApi } from '../LayoutApi';
import { PlusMinusApi } from '../PlusMinusApi';
import { PercentBarApi } from '../PercentBarApi';
import { QuickSearchApi } from '../QuickSearchApi';
import { ReminderApi } from '../ReminderApi';
import { ShortcutApi } from '../ShortcutApi';
import { SmartEditApi } from '../SmartEditApi';
import { SparklineColumnApi } from '../SparklineColumnApi';
import { SystemFilterApi } from '../SystemFilterApi';
import { SystemStatusApi } from '../SystemStatusApi';
import { UserInterfaceApi } from '../UserInterfaceApi';
import { UserFilterApi } from '../UserFilterApi';
import { NamedFilterApi } from '../NamedFilterApi';
import { ThemeApi } from '../ThemeApi';
import { GridApi } from '../GridApi';
import { IPushPullApi } from '../IPushPullApi';
import { ScheduleApi } from '../ScheduleApi';
import { GradientColumnApi } from '../GradientColumnApi';
export declare class AdaptableApiImpl implements AdaptableApi {
    protected adaptable: IAdaptable;
    actionColumnApi: ActionColumnApi;
    applicationApi: ApplicationApi;
    advancedSearchApi: AdvancedSearchApi;
    alertApi: AlertApi;
    auditEventApi: AuditEventApi;
    bulkUpdateApi: BulkUpdateApi;
    calendarApi: CalendarApi;
    calculatedColumnApi: CalculatedColumnApi;
    cellSummaryApi: CellSummaryApi;
    cellValidationApi: CellValidationApi;
    chartApi: ChartApi;
    columnCategoryApi: ColumnCategoryApi;
    columnChooserApi: ColumnChooserAPI;
    columnFilterApi: ColumnFilterApi;
    conditionalStyleApi: ConditionalStyleApi;
    configApi: ConfigApi;
    customSortApi: CustomSortApi;
    dashboardApi: DashboardApi;
    dataSourceApi: DataSourceApi;
    entitlementsApi: EntitlementsApi;
    eventApi: EventApi;
    exportApi: ExportApi;
    flashingCellApi: FlashingCellApi;
    updatedRowApi: UpdatedRowApi;
    formatColumnApi: FormatColumnApi;
    freeTextColumnApi: FreeTextColumnApi;
    gradientColumnApi: GradientColumnApi;
    gridApi: GridApi;
    internalApi: InternalApi;
    layoutApi: LayoutApi;
    plusMinusApi: PlusMinusApi;
    percentBarApi: PercentBarApi;
    quickSearchApi: QuickSearchApi;
    reminderApi: ReminderApi;
    scheduleApi: ScheduleApi;
    shortcutApi: ShortcutApi;
    smartEditApi: SmartEditApi;
    sparklineColumnApi: SparklineColumnApi;
    systemFilterApi: SystemFilterApi;
    systemStatusApi: SystemStatusApi;
    pluginsApi: PluginsApi;
    themeApi: ThemeApi;
    userInterfaceApi: UserInterfaceApi;
    userFilterApi: UserFilterApi;
    namedFilterApi: NamedFilterApi;
    iPushPullApi: IPushPullApi;
    glue42Api: Glue42ApiImpl;
    toolPanelApi: ToolPanelApi;
    constructor(adaptable: IAdaptable);
}
