import { ChartState } from '../../PredefinedConfig/ChartState';
import { UserFilterState } from '../../PredefinedConfig/UserFilterState';
import { ThemeState } from '../../PredefinedConfig/ThemeState';
import { SmartEditState } from '../../PredefinedConfig/SmartEditState';
import { ShortcutState } from '../../PredefinedConfig/ShortcutState';
import { QuickSearchState } from '../../PredefinedConfig/QuickSearchState';
import { PlusMinusState } from '../../PredefinedConfig/PlusMinusState';
import { LayoutState } from '../../PredefinedConfig/LayoutState';
import { FormatColumnState } from '../../PredefinedConfig/FormatColumnState';
import { FlashingCellState } from '../../PredefinedConfig/FlashingCellState';
import { ExportState } from '../../PredefinedConfig/ExportState';
import { DataSourceState } from '../../PredefinedConfig/DataSourceState';
import { DashboardState } from '../../PredefinedConfig/DashboardState';
import { CustomSortState } from '../../PredefinedConfig/CustomSortState';
import { ConditionalStyleState } from '../../PredefinedConfig/ConditionalStyleState';
import { ColumnFilterState } from '../../PredefinedConfig/ColumnFilterState';
import { CellValidationState } from '../../PredefinedConfig/CellValidationState';
import { CellSummaryState } from '../../PredefinedConfig/CellSummaryState';
import { CalendarState } from '../../PredefinedConfig/CalendarState';
import { CalculatedColumnState } from '../../PredefinedConfig/CalculatedColumnState';
import { BulkUpdateState } from '../../PredefinedConfig/BulkUpdateState';
import { AlertState } from '../../PredefinedConfig/AlertState';
import { AdvancedSearchState } from '../../PredefinedConfig/AdvancedSearchState';
import { RunTimeState } from '../../PredefinedConfig/RunTimeState';
import { AdaptableState } from '../../PredefinedConfig/AdaptableState';
import { ApiBase } from './ApiBase';
import { ActionColumnState } from '../../PredefinedConfig/ActionColumnState';
import { ApplicationState } from '../../PredefinedConfig/ApplicationState';
import { UpdatedRowState } from '../../PredefinedConfig/UpdatedRowState';
import { SparklineColumnState } from '../../PredefinedConfig/SparklineColumnState';
import { ColumnCategoryState } from '../../PredefinedConfig/ColumnCategoryState';
import { EntitlementState } from '../../PredefinedConfig/EntitlementState';
import { FreeTextColumnState } from '../../PredefinedConfig/FreeTextColumnState';
import { NamedFilterState } from '../../PredefinedConfig/NamedFilterState';
import { PercentBarState } from '../../PredefinedConfig/PercentBarState';
import { ReminderState } from '../../PredefinedConfig/ReminderState';
import { SystemFilterState } from '../../PredefinedConfig/SystemFilterState';
import { SystemStatusState } from '../../PredefinedConfig/SystemStatusState';
import { ToolPanelState } from '../../PredefinedConfig/ToolPanelState';
import { UserInterfaceState } from '../../PredefinedConfig/UserInterfaceState';
import { ConfigApi } from '../ConfigApi';
import { AdaptableStateKey } from '../../PredefinedConfig/Common/Types';
import { IPushPullState } from '../../PredefinedConfig/IPushPullState';
import { Glue42State } from '../../PredefinedConfig/Glue42State';
export declare class ConfigApiImpl extends ApiBase implements ConfigApi {
    configInit(): void;
    configClear(): void;
    configCopyAllStateToClipboard(): void;
    configCopyUserStateToClipboard(): void;
    configDeleteLocalStorage(): void;
    configGetAllState(): AdaptableState;
    private getUserStateKeys;
    configGetAllUserState(): RunTimeState[];
    configloadUserState(state: {
        [s: string]: RunTimeState;
    }): void;
    configGetUserStateByStateKey(stateKey: AdaptableStateKey, returnJson?: boolean): RunTimeState;
    configGetActionColumnState(returnJson?: boolean): ActionColumnState;
    configGetAdvancedSearchState(returnJson?: boolean): AdvancedSearchState;
    configGetAlertState(returnJson?: boolean): AlertState;
    configGetApplicationState(returnJson?: boolean): ApplicationState;
    configGetBulkUpdateState(returnJson?: boolean): BulkUpdateState;
    configGetCalculatedColumnState(returnJson?: boolean): CalculatedColumnState;
    configGetCalendarState(returnJson?: boolean): CalendarState;
    configGetCellSummaryState(returnJson?: boolean): CellSummaryState;
    configGetCellValidationState(returnJson?: boolean): CellValidationState;
    configGetChartState(returnJson?: boolean): ChartState;
    configGetColumnFilterState(returnJson?: boolean): ColumnFilterState;
    configGetColumnCategoryState(returnJson: boolean): ColumnCategoryState;
    configGetConditionalStyleState(returnJson?: boolean): ConditionalStyleState;
    configGetCustomSortState(returnJson?: boolean): CustomSortState;
    configGetDashboardState(returnJson?: boolean): DashboardState;
    configGetDataSourceState(returnJson?: boolean): DataSourceState;
    configGetEntitlementState(returnJson: boolean): EntitlementState;
    configGetExportState(returnJson?: boolean): ExportState;
    configGetFlashingCellState(returnJson?: boolean): FlashingCellState;
    configGetFreeTextColumnState(returnJson?: boolean): FreeTextColumnState;
    configGetFormatColumnState(returnJson?: boolean): FormatColumnState;
    configGetLayoutState(returnJson?: boolean): LayoutState;
    configGetNamedFilterState(returnJson?: boolean): NamedFilterState;
    configGetIPushPullState(returnJson?: boolean): IPushPullState;
    configGetGlue42State(returnJson?: boolean): Glue42State;
    configGetPercentBarState(returnJson?: boolean): PercentBarState;
    configGetPlusMinusState(returnJson?: boolean): PlusMinusState;
    configGetQuickSearchState(returnJson?: boolean): QuickSearchState;
    configGetReminderState(returnJson?: boolean): ReminderState;
    configGetShortcutState(returnJson?: boolean): ShortcutState;
    configGetSmartEditState(returnJson?: boolean): SmartEditState;
    configGetSparklineColumnState(returnJson?: boolean): SparklineColumnState;
    configGetSystemFilterState(returnJson?: boolean): SystemFilterState;
    configGetSystemStatusState(returnJson?: boolean): SystemStatusState;
    configGetThemeState(returnJson?: boolean): ThemeState;
    configGetToolPanelState(returnJson?: boolean): ToolPanelState;
    configGetUpdatedRowState(returnJson?: boolean): UpdatedRowState;
    configGetUserFilterState(returnJson?: boolean): UserFilterState;
    configGetUserInterfaceState(returnJson?: boolean): UserInterfaceState;
}
