import { ApiBase } from './ApiBase';
import { InternalApi } from '../InternalApi';
import { IUIConfirmation, AdaptableAlert } from '../../Utilities/Interface/IMessage';
import { ExportDestination } from '../../PredefinedConfig/Common/Enums';
import { Report } from '../../PredefinedConfig/ExportState';
import { SystemState } from '../../PredefinedConfig/SystemState';
import { Calendar } from '../../PredefinedConfig/CalendarState';
import { ChartData } from '../../PredefinedConfig/ChartState';
import { ChartVisibility } from '../../PredefinedConfig/Common/ChartEnums';
import { Action } from 'redux';
import { StrategyParams } from '../../View/Components/SharedProps/StrategyViewPopupProps';
import { AdaptableColumn } from '../../PredefinedConfig/Common/AdaptableColumn';
import { AdaptableMenuItem } from '../../PredefinedConfig/Common/Menu';
import { SelectedCellInfo } from '../../PredefinedConfig/Selection/SelectedCellInfo';
import { SelectedRowInfo } from '../../PredefinedConfig/Selection/SelectedRowInfo';
import { ChangeDirection } from '../../Utilities/Services/Interface/IDataService';
import { LiveReport } from '../Events/LiveDataChanged';
import { AdaptableFunctionName } from '../../PredefinedConfig/Common/Types';
import { ColumnSort } from '../../PredefinedConfig/Common/ColumnSort';
import { GridCell } from '../../PredefinedConfig/Selection/GridCell';
export declare class InternalApiImpl extends ApiBase implements InternalApi {
    startLiveReport(report: Report, pageName: string, exportDestination: ExportDestination.OpenfinExcel | ExportDestination.Glue42): void;
    stopLiveReport(report: Report, exportDestination: ExportDestination.OpenfinExcel | ExportDestination.Glue42): void;
    getSystemState(): SystemState;
    getAvailableCalendars(): Calendar[];
    setChartData(chartData: ChartData): void;
    setChartVisibility(chartVisbility: ChartVisibility): void;
    getSystemReports(): Report[];
    getLiveReports(): LiveReport[];
    getAdaptableAlerts(): AdaptableAlert[];
    showPopupConfirmation(confirmation: IUIConfirmation): void;
    showLoadingScreen(): void;
    hideLoadingScreen(): void;
    showPopupScreen(functionName: AdaptableFunctionName, componentName: string, popupParams?: StrategyParams, popupProps?: {
        [key: string]: any;
    }): void;
    hidePopupScreen(): void;
    setColumns(columns: AdaptableColumn[]): void;
    setMainMenuItems(menuItems: AdaptableMenuItem[]): void;
    setSelectedCells(selectedCellInfo: SelectedCellInfo): void;
    setSelectedRows(selectedRowInfo: SelectedRowInfo): void;
    showQuickFilterBar(): void;
    setPivotModeOn(): void;
    setPivotModeOff(): void;
    isGridInPivotMode(): boolean;
    addAdaptableColumn(AdaptableColumn: AdaptableColumn): void;
    setColumnSorts(columnSorts: ColumnSort[]): void;
    getUpdatedRowInfos(): any[];
    isRowInUpdatedRowInfo(primaryKeyValue: any, changeDirection: ChangeDirection): boolean;
    getCurrentLiveReports(): LiveReport[];
    isLiveReportRunning(): boolean;
    isOpenFinAvailable(): boolean;
    setGridCells(gridCells: GridCell[], internalUpdate: boolean, validateChange: boolean): void;
    setGridCell(gridCell: GridCell, internalUpdate: boolean, validateChange: boolean): void;
    private createDataChangedInfoFromGridCell;
    dispatchReduxAction(action: Action): void;
}
