import { GridOptions, RowNode, RowNodeTransaction } from '@ag-grid-community/all-modules';
import * as _ from 'lodash';
import { ColDef, ColGroupDef } from '@ag-grid-community/all-modules';
import { EmitterCallback } from '../Utilities/Emitter';
import { IAdaptableStore } from '../Redux/Store/Interface/IAdaptableStore';
import { ICalendarService } from '../Utilities/Services/Interface/ICalendarService';
import { IValidationService } from '../Utilities/Services/Interface/IValidationService';
import { IStyleService } from '../Utilities/Services/Interface/IStyleService';
import { IChartService } from '../Utilities/Services/Interface/IChartService';
import { ICalculatedColumnExpressionService } from '../Utilities/Services/Interface/ICalculatedColumnExpressionService';
import { IFreeTextColumnService } from '../Utilities/Services/Interface/IFreeTextColumnService';
import { IStrategyCollection } from '../Strategy/Interface/IStrategy';
import { DistinctCriteriaPairValue } from '../PredefinedConfig/Common/Enums';
import { IPPStyle } from '../Utilities/Interface/IPPStyle';
import { AdaptableColumn } from '../PredefinedConfig/Common/AdaptableColumn';
import { GridCell } from '../PredefinedConfig/Selection/GridCell';
import { IRawValueDisplayValuePair } from '../View/UIInterfaces';
import { IDataService } from '../Utilities/Services/Interface/IDataService';
import { DataChangedInfo } from '../PredefinedConfig/Common/DataChangedInfo';
import { IScheduleService } from '../Utilities/Services/Interface/IScheduleService';
import { IAuditLogService } from '../Utilities/Services/Interface/IAuditLogService';
import { ISearchService } from '../Utilities/Services/Interface/ISearchService';
import { PercentBar } from '../PredefinedConfig/PercentBarState';
import { CalculatedColumn } from '../PredefinedConfig/CalculatedColumnState';
import { FreeTextColumn } from '../PredefinedConfig/FreeTextColumnState';
import { VendorGridInfo, PivotDetails } from '../PredefinedConfig/LayoutState';
import { ActionColumn } from '../PredefinedConfig/ActionColumnState';
import { AdaptableTheme } from '../PredefinedConfig/ThemeState';
import { SparklineColumn } from '../PredefinedConfig/SparklineColumnState';
import { IAdaptable } from '../AdaptableInterfaces/IAdaptable';
import { IGlue42Service } from '../Utilities/Services/Interface/IGlue42Service';
import { IReportService } from '../Utilities/Services/Interface/IReportService';
import { AdaptableApi } from '../Api/AdaptableApi';
import { IPushPullService } from '../Utilities/Services/Interface/IPushPullService';
import { ILayoutService } from '../Utilities/Services/Interface/ILayoutService';
import { IStrategyService } from '../Utilities/Services/StrategyService';
import { IFilterService } from '../Utilities/Services/Interface/IFilterService';
import { AdaptableOptions } from '../AdaptableOptions/AdaptableOptions';
import { IAdaptableNoCodeWizard, IAdaptableNoCodeWizardOptions } from '../AdaptableInterfaces/IAdaptableNoCodeWizard';
import { AdaptablePlugin } from '../AdaptableOptions/AdaptablePlugin';
import { ColumnSort } from '../PredefinedConfig/Common/ColumnSort';
import { GradientColumn } from '../PredefinedConfig/GradientColumnState';
declare type RuntimeConfig = {
    instantiateGrid?: (...args: any[]) => any;
};
export declare class Adaptable implements IAdaptable {
    api: AdaptableApi;
    strategies: IStrategyCollection;
    AdaptableStore: IAdaptableStore;
    adaptableOptions: AdaptableOptions;
    vendorGridName: any;
    CalendarService: ICalendarService;
    DataService: IDataService;
    ValidationService: IValidationService;
    AuditLogService: IAuditLogService;
    ChartService: IChartService;
    StyleService: IStyleService;
    LayoutService: ILayoutService;
    StrategyService: IStrategyService;
    FilterService: IFilterService;
    CalculatedColumnExpressionService: ICalculatedColumnExpressionService;
    FreeTextColumnService: IFreeTextColumnService;
    ScheduleService: IScheduleService;
    SearchService: ISearchService;
    Glue42Service: IGlue42Service;
    PushPullService: IPushPullService;
    ReportService: IReportService;
    embedColumnMenu: boolean;
    private calculatedColumnPathMap;
    private useRowNodeLookUp;
    private abContainerElement;
    private gridContainerElement;
    gridOptions: GridOptions;
    isInitialised: boolean;
    private throttleOnDataChangedUser;
    private throttleOnDataChangedExternal;
    private agGridHelper;
    private renderGrid;
    private runtimeConfig?;
    private emitter;
    private _currentEditor;
    _on: (eventName: string, callback: EmitterCallback) => () => void;
    private _emit;
    static init(adaptableOptions: AdaptableOptions): AdaptableApi;
    constructor(adaptableOptions: AdaptableOptions, renderGrid?: boolean, runtimeConfig?: RuntimeConfig, _staticInit?: boolean);
    forPlugins(callback: (plugin: AdaptablePlugin) => any): void;
    lookupPlugins(propertyName: string, ...args: any): any;
    private initStore;
    private tryInstantiateAgGrid;
    debouncedSetColumnIntoStore: (() => void) & _.Cancelable;
    debouncedSaveGridLayout: (() => void) & _.Cancelable;
    debouncedSetSelectedCells: (() => void) & _.Cancelable;
    debouncedSetSelectedRows: (() => void) & _.Cancelable;
    debouncedFilterGrid: (() => void) & _.Cancelable;
    private filterOnUserDataChange;
    private filterOnExternalDataChange;
    private createFilterWrapper;
    private createQuickFilterWrapper;
    reloadGrid(): void;
    applyGridFiltering(): void;
    private applyDataChange;
    isGroupRowNode(rowNode: RowNode): boolean;
    private isDataInModel;
    isPinnedRowNode(rowNode: RowNode): boolean;
    clearGridFiltering(): void;
    clearColumnFiltering(columnIds: string[]): void;
    hideFilterFormPopup: Function;
    hideFilterForm(): void;
    setNewColumnListOrder(VisibleColumnList: Array<AdaptableColumn>): void;
    setColumnIntoStore(): void;
    private createAdaptableColumn;
    private applyStylingToColumn;
    private safeSetColDefs;
    private getQuickSearchClassName;
    private addQuickSearchStyleToColumn;
    createFunctionMenu(): void;
    getPrimaryKeyValueFromRowNode(rowNode: RowNode): any;
    gridHasCurrentEditValue(): boolean;
    getCurrentCellEditValue(): any;
    getActiveCell(): GridCell;
    saveGridLayout(): void;
    setSelectedCells(): void;
    setSelectedRows(): void;
    setValue(dataChangedInfo: DataChangedInfo, internalUpdate: boolean): void;
    cancelEdit(): void;
    getRowNodeIsSatisfiedFunction(id: any, distinctCriteria: DistinctCriteriaPairValue): (columnId: string) => any;
    getRowNodeIsSatisfiedFunctionFromRowNode(rowwNode: RowNode, distinctCriteria: DistinctCriteriaPairValue): (columnId: string) => any;
    setCustomSort(columnId: string, comparer: Function): void;
    removeCustomSort(columnId: string): void;
    getColumnValueDisplayValuePairDistinctList(columnId: string, distinctCriteria: DistinctCriteriaPairValue, visibleRowsOnly: boolean): Array<IRawValueDisplayValuePair>;
    getColumnValueDisplayValuePairList(columnId: string, visibleRowsOnly: boolean, onlyIncludeIds?: {
        [key: string]: boolean;
    }): Array<IRawValueDisplayValuePair>;
    private addDistinctColumnValue;
    private useRawValueForColumn;
    getDisplayValue(id: any, columnId: string): string;
    getDisplayValueFromRowNode(row: RowNode, columnId: string): string;
    getDisplayValueFromRawValue(columnId: string, rawValue: any): any;
    private getRenderedValue;
    getRawValueFromRowNode(rowNode: RowNode, columnId: string): any;
    getDataRowFromRowNode(rowNode: RowNode): any;
    getRowNodeForPrimaryKey(primaryKeyValue: any): any;
    getRowNodesForPrimaryKeys(primaryKeyValues: any[]): any[];
    setCellClassRules(cellClassRules: any, columnId: string, type: 'ConditionalStyle' | 'QuickSearch' | 'FlashingCell' | 'FormatColumn' | 'Alert' | 'UpdatedRow'): void;
    forAllRowNodesDo(func: (rowNode: any) => any): void;
    forAllVisibleRowNodesDo(func: (rowNode: any) => any): void;
    redraw(): void;
    redrawRow(rowNode: any): void;
    refreshCells(rowNodes: any[], columnIds: string[]): void;
    jumpToRow(rowNode: any): void;
    jumpToColumn(columnId: string): void;
    jumpToCell(columnId: string, rowNode: any): void;
    private forEachColumn;
    /**
     * This creates a clone of the current column definitions. If config.removeEmpty is true, will also remove empty column groups
     *
     */
    private mapColumnDefs;
    editCalculatedColumnInGrid(calculatedColumn: CalculatedColumn): void;
    removeCalculatedColumnFromGrid(calculatedColumnID: string): void;
    addCalculatedColumnToGrid(calculatedColumn: CalculatedColumn): void;
    getColumnDefs: () => (ColGroupDef | ColDef)[];
    addFreeTextColumnToGrid(freeTextColumn: FreeTextColumn): void;
    removeFreeTextColumnFromGrid(freeTextColumnId: string): void;
    editFreeTextColumnInGrid(freeTextColumn: FreeTextColumn): void;
    addActionColumnToGrid(actionColumn: ActionColumn): void;
    private addSpecialColumnToState;
    getFirstRowNode(): RowNode;
    destroy(): void;
    getDefaultIPPStyle(): IPPStyle;
    getCurrentIPPStyle(): IPPStyle;
    private getadaptableContainerElement;
    private getGridContainerElement;
    private initInternalGridLogic;
    private postSpecialColumnEditDelete;
    private addSpecialRendereredColumns;
    addSparklineColumn(sparklineColumn: SparklineColumn): void;
    addPercentBar(pcr: PercentBar): void;
    removeSparklineColumn(sparklineColumn: SparklineColumn): void;
    private onRowDataChanged;
    /**
     * There are a few things that we need to do AFTER we edit a cell and it makes sense to put them in one place
     */
    private performPostEditChecks;
    private checkChangedCellCurrentlySelected;
    removePercentBar(pcr: PercentBar): void;
    editPercentBar(pcr: PercentBar): void;
    removeGradientColumn(gradientColumn: GradientColumn): void;
    addGradientColumn(gradientColumn: GradientColumn): void;
    editGradientColumn(gradientColumn: GradientColumn): void;
    editSparklineColumn(sparklineColumn: SparklineColumn): void;
    private onSortChanged;
    getRowCount(): number;
    getColumnCount(): number;
    getVisibleRowCount(): number;
    getVisibleColumnCount(): number;
    selectColumn(columnId: string): void;
    setColumnSort(columnSorts: ColumnSort[]): void;
    setDataSource(dataSource: any): void;
    updateRows(dataRows: any[], config?: {
        batchUpdate?: boolean;
        callback?: (res: RowNodeTransaction) => void;
    }): void;
    addRows(dataRows: any[]): void;
    deleteRows(dataRows: any[]): void;
    private updateQuickSearchRangeVisibleColumn;
    private checkColumnsDataTypeSet;
    getVendorGridDefaultLayoutInfo(): VendorGridInfo;
    getVendorGridLayoutInfo(visibleCols: string[]): VendorGridInfo;
    setVendorGridLayoutInfo(vendorGridInfo: VendorGridInfo): void;
    setGroupedColumns(groupedCols: string[]): void;
    setPivotingDetails(pivotDetails: PivotDetails): void;
    setPivotMode(pivotDetails: PivotDetails, vendorGridInfo: VendorGridInfo): void;
    private turnOnPivoting;
    private turnOffPivoting;
    private setColumnVisible;
    private moveColumn;
    private setColumnState;
    isSelectable(): boolean;
    private isQuickFilterActive;
    showQuickFilter(): void;
    hideQuickFilter(): void;
    applyAdaptableTheme(theme: AdaptableTheme | string): void;
    setUpRowStyles(): void;
    clearRowStyles(): void;
    private applyFinalRendering;
    private getState;
}
export declare class AdaptableNoCodeWizard implements IAdaptableNoCodeWizard {
    private init;
    private adaptableOptions;
    private extraOptions;
    /**
     * @param adaptableOptions
     */
    constructor(adaptableOptions: AdaptableOptions, extraOptions?: IAdaptableNoCodeWizardOptions);
    render(container?: HTMLElement | null): void;
}
export {};
