import { AdaptableColumn } from '../../PredefinedConfig/Common/AdaptableColumn';
import { DataType } from '../../PredefinedConfig/Common/Enums';
import { ColumnCategory } from '../../PredefinedConfig/ColumnCategoryState';
export declare function isSpecialColumn(columnId: string): boolean;
export declare function isNumericColumn(column: AdaptableColumn): boolean;
export declare function getColumnDataTypeFromColumnId(columnId: string, columns: AdaptableColumn[]): 'String' | 'Number' | 'NumberArray' | 'Boolean' | 'Date' | 'Object' | 'Unknown';
export declare function getFriendlyNameFromColumn(columnId: string, column: AdaptableColumn): string;
export declare function getFriendlyNameFromColumnId(columnId: string, columns: AdaptableColumn[]): string;
export declare function getFriendlyNamesFromColumnIds(columnIds: string[], columns: AdaptableColumn[]): string[];
export declare function getColumnIdFromFriendlyName(friendlyName: string, columns: AdaptableColumn[]): string;
export declare function getColumnIdsFromFriendlyNames(friendlyNames: string[], columns: AdaptableColumn[]): string[];
export declare function getColumnsFromFriendlyNames(friendlyNames: string[], columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getColumnFromId(columnId: string, columns: AdaptableColumn[], logWarning?: boolean): AdaptableColumn;
export declare function getColumnFromFriendlyName(columnName: string, columns: AdaptableColumn[], logWarning?: boolean): AdaptableColumn;
export declare function getColumnsOfType(columns: AdaptableColumn[], dataType: DataType): AdaptableColumn[];
export declare function getNumericColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getNumericArrayColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getStringColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getDateColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getBooleanColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getColumnCategoryFromColumnCategories(columnId: string, ColumnCategoryns: ColumnCategory[]): string;
export declare function getSortableColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getGroupableColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getPivotableColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare function getAggregetableColumns(columns: AdaptableColumn[]): AdaptableColumn[];
export declare const ColumnHelper: {
    isSpecialColumn: typeof isSpecialColumn;
    isNumericColumn: typeof isNumericColumn;
    getColumnDataTypeFromColumnId: typeof getColumnDataTypeFromColumnId;
    getFriendlyNameFromColumn: typeof getFriendlyNameFromColumn;
    getFriendlyNameFromColumnId: typeof getFriendlyNameFromColumnId;
    getFriendlyNamesFromColumnIds: typeof getFriendlyNamesFromColumnIds;
    getColumnsFromFriendlyNames: typeof getColumnsFromFriendlyNames;
    getColumnFromId: typeof getColumnFromId;
    getColumnFromFriendlyName: typeof getColumnFromFriendlyName;
    getColumnsOfType: typeof getColumnsOfType;
    getNumericColumns: typeof getNumericColumns;
    getNumericArrayColumns: typeof getNumericArrayColumns;
    getStringColumns: typeof getStringColumns;
    getDateColumns: typeof getDateColumns;
    getBooleanColumns: typeof getBooleanColumns;
    getColumnCategoryFromColumnCategories: typeof getColumnCategoryFromColumnCategories;
    getSortableColumns: typeof getSortableColumns;
    getGroupableColumns: typeof getGroupableColumns;
    getPivotableColumns: typeof getPivotableColumns;
    getAggregetableColumns: typeof getAggregetableColumns;
    getColumnIdFromFriendlyName: typeof getColumnIdFromFriendlyName;
    getColumnIdsFromFriendlyNames: typeof getColumnIdsFromFriendlyNames;
};
export default ColumnHelper;
