import { CSSProperties } from 'react';
import { EditableConfigEntityState } from './Components/SharedProps/EditableConfigEntityState';
import { StatusColour, MessageType } from '../PredefinedConfig/Common/Enums';
import { AdaptableStyle } from '../PredefinedConfig/Common/AdaptableStyle';
import { ExpressionBuilderPageState } from './ExpressionBuilder/ExpressionBuilderPage';
import { Expression } from '../PredefinedConfig/Common/Expression';
import { Schedule } from '../PredefinedConfig/Common/Schedule';
import { AdaptableAlert } from '../Utilities/Interface/IMessage';
import { AdaptableOptions } from '../types';
export declare const BLACK: string;
export declare const WHITE: string;
export declare const LIGHT_GRAY: string;
export declare const GRAY: string;
export declare const BROWN: string;
export declare const DARK_GREEN: string;
export declare const GREEN: string;
export declare const LIME_GREEN: string;
export declare const YELLOW: string;
export declare const LIGHT_YELLOW: string;
export declare const DARK_BLUE: string;
export declare const BLUE: string;
export declare const LIGHT_BLUE: string;
export declare const CYAN: string;
export declare const MAGENTA: string;
export declare const PURPLE: string;
export declare const DARK_RED: string;
export declare const RED: string;
export declare const LIGHT_RED: string;
export declare const ORANGE: string;
export declare function getHexForName(name: string): string;
export declare function getDefaultColors(): string[];
export declare function getEmptyConfigState(): EditableConfigEntityState;
export declare function getExpressionBuilderState(expression: Expression): ExpressionBuilderPageState;
export declare function getExpressionBuilderStateWithColumn(expression: Expression, columnId: string): ExpressionBuilderPageState;
export declare function getDescriptionForDataType(dataType: 'String' | 'Number' | 'NumberArray' | 'Boolean' | 'Date' | 'Object' | 'Unknown'): "string" | "number" | "date";
export declare function getPlaceHolderforDataType(dataType: 'String' | 'Number' | 'NumberArray' | 'Boolean' | 'Date' | 'Object' | 'Unknown'): "Enter Value" | "Enter Number" | "Enter Date";
export declare function getModalContainer(adaptableOptions: AdaptableOptions, document: Document): HTMLElement;
export declare function getChartContainer(adaptableOptions: AdaptableOptions, document: Document, showModal: boolean): HTMLElement;
export declare function isValidUserChartContainer(adaptableOptions: AdaptableOptions, document: Document): boolean;
export declare function IsNotEmptyStyle(style: AdaptableStyle): boolean;
export declare function getMessageTypeByStatusColour(statusColour: StatusColour): MessageType;
export declare function getGlyphByMessageType(messageType: MessageType): string;
export declare function getColorByMessageType(messageType: MessageType): string;
export declare function getStyleForStatusColour(statusColour: StatusColour): CSSProperties;
export declare function getStyleForMessageType(messageType: MessageType): CSSProperties;
export declare function getGlyphForStatusColour(statusColour: StatusColour): string;
export declare function getGlyphForMessageType(messageType: MessageType): string;
export declare function getButtonToneForMessageType(messageType: MessageType): 'info' | 'warning' | 'error' | 'success';
export declare function getScheduleDescription(schedule: Schedule): string;
export declare function getMessageTypeFromAdaptableAlerts(adaptableAlerts: AdaptableAlert[]): MessageType;
export declare function getButtonColourForAdaptableAlerts(adaptableAlerts: AdaptableAlert[], messageTypeColor: string): string;
export declare function getButtonTextColourForArrayandMessageType(adaptableAlerts: AdaptableAlert[], messageType: MessageType): string;
export declare function getButtonTextColourForMessageType(messageType: MessageType): string;
export declare const UIHelper: {
    getHexForName: typeof getHexForName;
    getDefaultColors: typeof getDefaultColors;
    getEmptyConfigState: typeof getEmptyConfigState;
    getExpressionBuilderState: typeof getExpressionBuilderState;
    getExpressionBuilderStateWithColumn: typeof getExpressionBuilderStateWithColumn;
    getDescriptionForDataType: typeof getDescriptionForDataType;
    getPlaceHolderforDataType: typeof getPlaceHolderforDataType;
    getModalContainer: typeof getModalContainer;
    getChartContainer: typeof getChartContainer;
    isValidUserChartContainer: typeof isValidUserChartContainer;
    IsNotEmptyStyle: typeof IsNotEmptyStyle;
    getMessageTypeByStatusColour: typeof getMessageTypeByStatusColour;
    getGlyphByMessageType: typeof getGlyphByMessageType;
    getStyleForStatusColour: typeof getStyleForStatusColour;
    getGlyphForStatusColour: typeof getGlyphForStatusColour;
    getButtonToneForMessageType: typeof getButtonToneForMessageType;
    getScheduleDescription: typeof getScheduleDescription;
    getColorByMessageType: typeof getColorByMessageType;
    getGlyphForMessageType: typeof getGlyphForMessageType;
    getStyleForMessageType: typeof getStyleForMessageType;
    getMessageTypeFromAdaptableAlerts: typeof getMessageTypeFromAdaptableAlerts;
    getButtonColourForAdaptableAlerts: typeof getButtonColourForAdaptableAlerts;
    getButtonTextColourForArrayandMessageType: typeof getButtonTextColourForArrayandMessageType;
    getButtonTextColourForMessageType: typeof getButtonTextColourForMessageType;
};
export default UIHelper;
