import { MessageType, LeafExpressionOperator, RangeOperandType, ActionMode, ScheduleType } from '../PredefinedConfig/Common/Enums';
import { CustomSort } from '../PredefinedConfig/CustomSortState';
import { DataSource } from '../PredefinedConfig/DataSourceState';
import { PieChartDefinition, CategoryChartDefinition, SparklinesChartDefinition } from '../PredefinedConfig/ChartState';
import { CalculatedColumn } from '../PredefinedConfig/CalculatedColumnState';
import { PlusMinusRule } from '../PredefinedConfig/PlusMinusState';
import { AdaptableAlert } from './Interface/IMessage';
import { AlertDefinition } from '../PredefinedConfig/AlertState';
import { AdvancedSearch } from '../PredefinedConfig/AdvancedSearchState';
import { IRangeEvaluation } from './Helpers/ExpressionHelper';
import { ColumnCategory } from '../PredefinedConfig/ColumnCategoryState';
import { VendorGridInfo, Layout, PivotDetails } from '../PredefinedConfig/LayoutState';
import { CellValidationRule } from '../PredefinedConfig/CellValidationState';
import { PercentBar } from '../PredefinedConfig/PercentBarState';
import { UserFilter } from '../PredefinedConfig/UserFilterState';
import { Report, ReportSchedule } from '../PredefinedConfig/ExportState';
import { AdaptableColumn } from '../PredefinedConfig/Common/AdaptableColumn';
import { FlashingCell } from '../PredefinedConfig/FlashingCellState';
import { Schedule, BaseSchedule } from '../PredefinedConfig/Common/Schedule';
import { Shortcut } from '../PredefinedConfig/ShortcutState';
import { ConditionalStyle } from '../PredefinedConfig/ConditionalStyleState';
import { FormatColumn } from '../PredefinedConfig/FormatColumnState';
import { FreeTextColumn } from '../PredefinedConfig/FreeTextColumnState';
import { Expression, QueryRange } from '../PredefinedConfig/Common/Expression';
import { ColumnFilter } from '../PredefinedConfig/ColumnFilterState';
import { AdaptableStyle } from '../PredefinedConfig/Common/AdaptableStyle';
import { CellSummmary } from '../PredefinedConfig/Selection/CellSummmary';
import { SparklineColumn } from '../PredefinedConfig/SparklineColumnState';
import { DataChangedInfo } from '../PredefinedConfig/Common/DataChangedInfo';
import { ColumnSort } from '../PredefinedConfig/Common/ColumnSort';
import { IPushPullReport, IPushPullSchedule } from '../PredefinedConfig/IPushPullState';
import { ReminderSchedule } from '../PredefinedConfig/ReminderState';
import { Glue42Report, Glue42Schedule } from '../PredefinedConfig/Glue42State';
import { GradientColumn } from '../PredefinedConfig/GradientColumnState';
export declare function CreateEmptyCustomSort(): CustomSort;
export declare function CreateEmptyDataSource(): DataSource;
export declare function CreateEmptyPieChartDefinition(): PieChartDefinition;
export declare function CreateEmptySparklinesChartDefinition(): SparklinesChartDefinition;
export declare function CreateEmptyCategoryChartDefinition(): CategoryChartDefinition;
export declare function CreateEmptyCalculatedColumn(): CalculatedColumn;
export declare function CreateEmptyPlusMinusRule(): PlusMinusRule;
export declare function CreateEmptyAlert(): AdaptableAlert;
export declare function CreateAlert(alertHeader: string, alertMessage: string, alertDefinition: AlertDefinition, dataChangedInfo: DataChangedInfo): AdaptableAlert;
export declare function CreateEmptyAlertDefinition(): AlertDefinition;
export declare function CreateInternalAlertDefinitionForMessages(messageType: MessageType, showPopup?: boolean): AlertDefinition;
export declare function CreateEmptyAdvancedSearch(): AdvancedSearch;
export declare function CreateEmptyColumnCategory(): ColumnCategory;
export declare function CreateEmptyRange(): QueryRange;
export declare function CreateEmptyColumnSort(): ColumnSort;
export declare function CreateEmptyCellValidation(): CellValidationRule;
export declare function CreateEmptyPercentBar(): PercentBar;
export declare function CreateEmptyGradientColumn(): GradientColumn;
export declare function CreateEmptySparklineColumn(): SparklineColumn;
export declare function CreateEmptyUserFilter(): UserFilter;
export declare function CreateEmptyReport(): Report;
export declare function CreateDefaultFlashingCell(column: AdaptableColumn, upColor: string, downColor: string, duration: 250 | 500 | 750 | 1000): FlashingCell;
export declare function CreateEmptyBaseSchedule(scheduleType: ScheduleType): BaseSchedule;
export declare function CreateEmptyReminderSchedule(): ReminderSchedule;
export declare function CreateEmptyReportSchedule(): ReportSchedule;
export declare function CreateEmptyIPushPullReport(): IPushPullReport;
export declare function CreateEmptyGlue42Report(): Glue42Report;
export declare function CreateEmptyIPushPullSchedule(): IPushPullSchedule;
export declare function CreateEmptyGlue42Schedule(): Glue42Schedule;
export declare function CreateEmptyReminder(): ReminderSchedule;
export declare function CreateIPushPullSchedule(iPushPullReport: IPushPullReport): IPushPullSchedule;
export declare function CreateGlue42Schedule(glue42Report: Glue42Report): Glue42Schedule;
export declare function CreateReportSchedule(reportName: string): ReportSchedule;
export declare function CreateEmptySchedule(): Schedule;
export declare function CreateEmptyShortcut(): Shortcut;
export declare function CreateEmptyConditionalStyle(): ConditionalStyle;
export declare function CreateEmptyFormatColumn(): FormatColumn;
export declare function CreateEmptyFreeTextColumn(): FreeTextColumn;
export declare function CreateEmptyLayout(): Layout;
export declare function CreateLayout(columns: AdaptableColumn[], columnSorts: ColumnSort[], vendorGridInfo: VendorGridInfo, name: string): Layout;
export declare function CreateEmptyPivotDetails(): PivotDetails;
export declare function CreateColumnFilter(columnId: string, expression: Expression): ColumnFilter;
export declare function CreateUserFilterFromColumnFilter(columnFilter: ColumnFilter, name: string): UserFilter;
export declare function CreateRange(operator: LeafExpressionOperator, operand1: any, operand2: any, rangeOperandType: RangeOperandType, rangeOperandType2: RangeOperandType): QueryRange;
export declare function CreateRangeEvaluation(operator: LeafExpressionOperator, operand1: any, operand2: any, newValue: any, initialValue: any, columnId: string): IRangeEvaluation;
export declare function CreateCellValidationRule(columnId: string, range: QueryRange, actionMode: ActionMode, expression: Expression): CellValidationRule;
export declare function CreateEmptyStyle(): AdaptableStyle;
export declare function CreateEmptyCellSummmary(): CellSummmary;
export declare function CreateSystemReports(): Array<Report>;
export declare const ObjectFactory: {
    CreateEmptyCustomSort: typeof CreateEmptyCustomSort;
    CreateEmptyDataSource: typeof CreateEmptyDataSource;
    CreateEmptyPieChartDefinition: typeof CreateEmptyPieChartDefinition;
    CreateEmptySparklinesChartDefinition: typeof CreateEmptySparklinesChartDefinition;
    CreateEmptyCategoryChartDefinition: typeof CreateEmptyCategoryChartDefinition;
    CreateEmptyCalculatedColumn: typeof CreateEmptyCalculatedColumn;
    CreateEmptyPlusMinusRule: typeof CreateEmptyPlusMinusRule;
    CreateEmptyAlert: typeof CreateEmptyAlert;
    CreateAlert: typeof CreateAlert;
    CreateEmptyAlertDefinition: typeof CreateEmptyAlertDefinition;
    CreateInternalAlertDefinitionForMessages: typeof CreateInternalAlertDefinitionForMessages;
    CreateEmptyAdvancedSearch: typeof CreateEmptyAdvancedSearch;
    CreateEmptyColumnCategory: typeof CreateEmptyColumnCategory;
    CreateEmptyRange: typeof CreateEmptyRange;
    CreateEmptyColumnSort: typeof CreateEmptyColumnSort;
    CreateEmptyCellValidation: typeof CreateEmptyCellValidation;
    CreateEmptyPercentBar: typeof CreateEmptyPercentBar;
    CreateEmptyGradientColumn: typeof CreateEmptyGradientColumn;
    CreateEmptySparklineColumn: typeof CreateEmptySparklineColumn;
    CreateEmptyUserFilter: typeof CreateEmptyUserFilter;
    CreateEmptyReport: typeof CreateEmptyReport;
    CreateDefaultFlashingCell: typeof CreateDefaultFlashingCell;
    CreateEmptyReminder: typeof CreateEmptyReminder;
    CreateEmptyBaseSchedule: typeof CreateEmptyBaseSchedule;
    CreateEmptyReminderSchedule: typeof CreateEmptyReminderSchedule;
    CreateEmptyReportSchedule: typeof CreateEmptyReportSchedule;
    CreateEmptyIPushPullSchedule: typeof CreateEmptyIPushPullSchedule;
    CreateEmptyIPushPullReport: typeof CreateEmptyIPushPullReport;
    CreateIPushPullSchedule: typeof CreateIPushPullSchedule;
    CreateGlue42Schedule: typeof CreateGlue42Schedule;
    CreateReportSchedule: typeof CreateReportSchedule;
    CreateEmptySchedule: typeof CreateEmptySchedule;
    CreateEmptyShortcut: typeof CreateEmptyShortcut;
    CreateEmptyConditionalStyle: typeof CreateEmptyConditionalStyle;
    CreateEmptyFormatColumn: typeof CreateEmptyFormatColumn;
    CreateEmptyFreeTextColumn: typeof CreateEmptyFreeTextColumn;
    CreateEmptyLayout: typeof CreateEmptyLayout;
    CreateLayout: typeof CreateLayout;
    CreateEmptyPivotDetails: typeof CreateEmptyPivotDetails;
    CreateColumnFilter: typeof CreateColumnFilter;
    CreateUserFilterFromColumnFilter: typeof CreateUserFilterFromColumnFilter;
    CreateRange: typeof CreateRange;
    CreateRangeEvaluation: typeof CreateRangeEvaluation;
    CreateCellValidationRule: typeof CreateCellValidationRule;
    CreateEmptyStyle: typeof CreateEmptyStyle;
    CreateEmptyCellSummmary: typeof CreateEmptyCellSummmary;
    CreateSystemReports: typeof CreateSystemReports;
    CreateEmptyGlue42Schedule: typeof CreateEmptyGlue42Schedule;
    CreateEmptyGlue42Report: typeof CreateEmptyGlue42Report;
};
export default ObjectFactory;
